animals = ['bear', 'ruby', 'peacock', 'kangaroo', 'whale', 'platypus']
puts "---EXERCISES---"
puts "#1"
puts "The animal at index 1 is 'ruby'"
puts "The animal at index 1 is #{animals[1]}"
puts ""
puts '#2'
puts "The third animal is peacock"
puts "The third animal is #{animals[2]}"
puts ""
puts "#3"
puts "The first animal is 'bear'"
puts "The first animal is #{animals[0]}"
puts ""
puts "#4"
puts "The animal at 3 is 'kangaroo'"
puts "The animal at 3 is #{animals[3]}"
puts ""
puts "#5"
puts "The fifth animal is 'whale'"
puts "The fifth animal is #{animals[4]}"
puts ""
puts "#6"
puts "The animal at 2 is 'peacock'"
puts "The animal at 2 is #{animals[2]}"
puts ""
puts "#7"
puts "The sixth animal is 'platypus'"
puts "The sixth animal is #{animals[5]}"
puts ""
puts "#8"
puts "The animal at 4 is 'whale'"
puts "The animal at 4 is #{animals[4]}"

puts "---STUDY DRILLS---"
puts "#1"
puts "Question: With what you know of the difference between these types of numbers, can you explain why the year 2010 in 'January 1, 2010,' really is 2010 and not 2009? (Hint: you can't pick years at random.)"
puts ""
puts "Answer: Years are something that we count in sequence. The order matters, and we don't typically conceptualize anything as coming before the first year (it was the first, by definition nothing came before it!). Thus, years in the Julian calendar are ordinal, Year 1 really was the first year, and as we continue that pattern forward we see that 2010 really IS the 2010th year. Centuries, though... dates for centuries are zero indexed. The first century happened in the year 001! So, in a roundabout relationship, centuries could be said to be zero indexed!"
puts ""
puts "#2"
puts "Question: write some more arrays and work out similar indexes until you can translate them"
sarcophagus = ["Air", "Earth", "Water", "Fire", "Mila Jovovich", "The Great Darkness"]
puts "I made one called 'sarcophagus' because the 90's were the best decade, and it looks like #{sarcophagus}"
puts "The first element is 'Air'"
puts "The fifth element is 'Mila Jovovich'"
puts "The element at index 3 is 'Fire'"
puts "The element at index 0 is 'Air'"
puts ""
puts "#3"
puts "The first element is #{sarcophagus[0]}"
puts "The fifth element is #{sarcophagus[4]}"
puts "The element at index 3 is #{sarcophagus[3]}"
puts "The element at index 0 is #{sarcophagus[0]}"
